### ISSUE TITLE
The 1.9.7 tarball contains code that does not build on Python 3.11

### ISSUE THREAD

**Issue by tbabej** [mdtraj/mdtraj#1761]
Attempting to install `mdtraj` using `pip` in a Python 3.11 environment will result in the following problem:

```
$ pip install mdtraj
(... abbreviated ...)
      mdtraj/geometry/drid.cpp:230:12: fatal error: longintrepr.h: No such file or directory
        230 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
```

However, installing the same release (1.9.7) from source will work just fine:
```
$ pip install git+https://github.com/mdtraj/mdtraj@1.9.7
(... abbreviated ...)
Successfully installed astunparse-1.6.3 mdtraj-1.9.7 numpy-1.24.1 pyparsing-3.0.9 scipy-1.9.3 six-1.16.0 wheel-0.38.4
```

This is due to the fact that the release tarball ships `cpp` files that uncoditionally include `longintrepr.h`, which no longer works under Python 3.11. If newer Cython is used to generate the `cpp` files from the `pyx`, the `longintrepr.h` include is under a conditional:

```
  #if PY_MAJOR_VERSION < 3
    #include "longintrepr.h"
  #endif
```

In order to fix this, we will need to cut a new release using a Cython that contains https://github.com/cython/cython/pull/4428, that is at least 0.29.25. In the meantime, the workaround of using
```
$ pip install git+https://github.com/mdtraj/mdtraj@1.9.7
```

to install from source works.

**Comment by mattwthompson** [comment]
Right, no release supports 3.11 yet. The fix is in progress https://github.com/mdtraj/mdtraj/pull/1758

**Comment by RaulPPelaez** [comment]
Bumping here to kindly ask for a new python 3.11 pip release now that #1758 was merged.

**Comment by mattwthompson** [comment]
1.9.8 is released, which should include support for Python 3.11 and Apple Silicon. If there are any deployment issues please note them in the release discussion: https://github.com/mdtraj/mdtraj/discussions/1793
