### ISSUE TITLE
ConvertDataToHDF.py throwing odd error, with the problem coming from hdf5.py?

### ISSUE THREAD

**Issue by sryckbos** [mdtraj/mdtraj#265]
When I'm trying to use ConvertDataToHDF.py, I'm getting the following error:
"AttributeError: topology_object fails to implement thechains() -> residue() -> atoms() and bond() protocol. Specifically, we encountered the following 'NoneType' object has no attribute 'symbol' "

Is this a similar problem to the lh5.py one?  Is it also confused about the vsites?  ConvertDataToHDF.py worked on 2.7 with this exact same dataset.
