### ISSUE TITLE
fatal error: 'numpy/arrayobject.h' file not found

### ISSUE THREAD

**Issue by khuston** [mdtraj/mdtraj#1116]
When I tried installing mdtraj through pip, I got an error when building the various extensions. For example:

    mdtraj/rmsd/_lprmsd.cpp:304:10: fatal error: 'numpy/arrayobject.h' file not found

I fixed the problem for myself by adding `numpy.get_include()` to `include_dirs` for each extension in `setup.py`. This was on OS X 10.10.5.

**Comment by marscher** [comment]
Am 12.05.2016 um 17:15 schrieb Kyle Huston:
> When I tried installing mdtraj through pip, I got an error when building the various extensions. For example:
>
> |mdtraj/rmsd/_lprmsd.cpp:304:10: fatal error: 'numpy/arrayobject.h' file not found |
>
> I fixed the problem for myself by adding |numpy.get_include()| to |include_dirs| for each extension in |setup.py|. This was on OS X 10.10.5.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/mdtraj/mdtraj/issues/1116>
>
Was numpy present on your system before you installed mdtraj?

**Comment by khuston** [comment]
Yes

**Comment by marscher** [comment]
Then this file should have been found by mdtrajs setup and the include path should also been added to the extension. What version of setuptools do you have?

python -c "import setuptools; print(setuptools.__version__)"

**Comment by khuston** [comment]
I had 19.7, and after upgrading to 21.0, the installation worked -- my bad. Thanks for the help.

**Comment by marscher** [comment]
Actually this is not your fault. We use a method based on setuptools to obtain the include path from numpy which should be robust, even with the version you used.
